"""device table

Revision ID: c425c0fe1e30
Revises: 
Create Date: 2018-08-14 09:36:36.024788

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c425c0fe1e30'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('device',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mac', sa.String(length=20), nullable=True),
    sa.Column('ip', sa.String(length=25), nullable=True),
    sa.Column('last_seen', sa.DateTime(), nullable=True),
    sa.Column('first_seen', sa.DateTime(), nullable=True),
    sa.Column('nampHTML', sa.String(length=40), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_device_first_seen'), 'device', ['first_seen'], unique=False)
    op.create_index(op.f('ix_device_ip'), 'device', ['ip'], unique=False)
    op.create_index(op.f('ix_device_last_seen'), 'device', ['last_seen'], unique=False)
    op.create_index(op.f('ix_device_mac'), 'device', ['mac'], unique=True)
    op.create_index(op.f('ix_device_nampHTML'), 'device', ['nampHTML'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_device_nampHTML'), table_name='device')
    op.drop_index(op.f('ix_device_mac'), table_name='device')
    op.drop_index(op.f('ix_device_last_seen'), table_name='device')
    op.drop_index(op.f('ix_device_ip'), table_name='device')
    op.drop_index(op.f('ix_device_first_seen'), table_name='device')
    op.drop_table('device')
    # ### end Alembic commands ###
