"""device table

Revision ID: c53b2d8b3536
Revises: c425c0fe1e30
Create Date: 2018-08-17 05:23:54.753565

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c53b2d8b3536'
down_revision = 'c425c0fe1e30'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('device', sa.Column('hostname', sa.String(length=100), nullable=True))
    op.add_column('device', sa.Column('lastboot', sa.String(length=50), nullable=True))
    op.add_column('device', sa.Column('os', sa.String(length=100), nullable=True))
    op.add_column('device', sa.Column('ports', sa.String(length=100), nullable=True))
    op.add_column('device', sa.Column('vendor', sa.String(length=50), nullable=True))
    op.create_index(op.f('ix_device_hostname'), 'device', ['hostname'], unique=False)
    op.create_index(op.f('ix_device_lastboot'), 'device', ['lastboot'], unique=False)
    op.create_index(op.f('ix_device_os'), 'device', ['os'], unique=False)
    op.create_index(op.f('ix_device_ports'), 'device', ['ports'], unique=False)
    op.create_index(op.f('ix_device_vendor'), 'device', ['vendor'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_device_vendor'), table_name='device')
    op.drop_index(op.f('ix_device_ports'), table_name='device')
    op.drop_index(op.f('ix_device_os'), table_name='device')
    op.drop_index(op.f('ix_device_lastboot'), table_name='device')
    op.drop_index(op.f('ix_device_hostname'), table_name='device')
    op.drop_column('device', 'vendor')
    op.drop_column('device', 'ports')
    op.drop_column('device', 'os')
    op.drop_column('device', 'lastboot')
    op.drop_column('device', 'hostname')
    # ### end Alembic commands ###
